### PR TITLE
Use PythonLibs instead of PythonLibsCustom to fix lib detection problems (fixes #35)

### LINKED ISSUE #35: Python version detection appears to be broken
At least here on arch linux the usage of `PythonLibsCustom` over `PythonLibs` makes all the python3 builds to fail when loaded from within vim eg. by doing `:py3 import cpsm_py` with this stack trace
```
Traceback (most recent call last):                                                                                                                             
  File "<string>", line 1, in <module>
ImportError: ~/.vim/bundle/cpsm/autoload/cpsm_py.so: undefined symbol: forkpty
```
Moreover the linking phase happens instantly when using `PythonLibs` instead of taking the usual ~2 mins.

### PR DESCRIPTION
**Pull request by svenstaro**
I think using PythonLibs is the proper way to do this. With PythonLibsCustom I had problems where it detected the wrong libraries (on Arch Linux). Additionally, by using the system-provided file, it will be maintained upstream which means less code for you to worry about. This also fixes #35.

### CODE REVIEW

**Comment by svenstaro** [comment]
@nixprime Hey, could you take a look?

**Comment by nixprime** [comment]
PythonLibsCustom exists since PythonLibs does not consistently work on Mac OS X (see https://github.com/nixprime/cpsm/commit/01e2392af323640674ef58134b26f8746bfad74a). I'll try to set up an Arch Linux VM to repro the original issue, but switching to PythonLibs altogether isn't an option.

**Comment by svenstaro** [comment]
Ok fair enough. How about we leave your custom script in and only run it in case we're on `APPLE`?

**Comment by Shougo** [comment]
Any progress?

**Comment by vimeitor** [comment]
Can confirm that this PR fixes the issue for me as well.

**Comment by svenstaro** [comment]
This has been fixed by @nixprime in some other way.

**Comment by mrinterweb** [comment]
I just updated to the latest version of cpsm, and I'm now getting the same error.

**Pull request closed without merging**
